
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, PasswordField, BooleanField, DateTimeField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class ContactForm(FlaskForm):
    first_name = StringField('First Name')
    middle_name = StringField('Middle Name')
    last_name = StringField('Last Name')
    prefix = SelectField('Prefix', choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('miss', 'Miss'), ('dr', 'Dr.'), ('prof', 'Prof.')])
    suffix = SelectField('Suffix', choices=[('jr', 'Jr'), ('sr', 'Sr'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV')])
    legal_name = StringField('Full Legal Name')
    about = TextAreaField('About')
    country_code = StringField('Country Code')
    home_phone = StringField('Home Phone')
    work_phone = StringField('Work Phone')
    other_phone = StringField('Other Phone')
    email = StringField('Email')
    email2 = StringField('Other Email')
    street1 = StringField('Street')
    city1 = StringField('City')
    postal_code1 = StringField('Potal Code')
    state1 = StringField('State/Province')
    street2 = StringField('Street')
    city2 = StringField('City')
    postal_code2 = StringField('Potal Code')
    state2 = StringField('State/Province')
    company_name = StringField('Company Name')#+
    company_street = StringField('Street')
    company_city = StringField('City')
    company_state = StringField('State/Province')
    company_postal = StringField('Postal Code')
    company_country = StringField('Country')
    company_title = StringField('Title')
    company_department = StringField('Department')
    birthday = DateTimeField('Birthday')
    home_anniversary = DateTimeField('Home Anniversary')

    agent = StringField('Agent')
    vendor = StringField('Vendor')
    investor = StringField('Investor')
    loan_officer = StringField('Loan Officer')
    talent = StringField('Talent')
    builder = StringField('Builder')
    reo = StringField('REO')
    short_sale = StringField('Short Sale')
    expired = DateTimeField('Expired')
    fsbo = StringField('FSBO')
    sphere = StringField('Sphere')
    allied_resource = StringField('Allied Resource')
    referral_sources = StringField('Referral Sources')
    first_time = BooleanField('First Time Buyer')
    tags = StringField('Tags')
    notes = TextAreaField('Notes')
    source = StringField('Source')
    #date_added = DateTimeField('Date Added')
    facebook = StringField('Facebook')
    twitter = StringField('Twitter')
    linkedin = StringField('LinkedIn')
    google = StringField('Google+')
    pintrest = StringField('Pintrest')
    instagram = StringField('Instagram')
    houzz = StringField('Houzz')

    submit = SubmitField('Add Contact')
