
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, PasswordField, BooleanField, DateTimeField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class ContactForm(FlaskForm):
    first_name = StringField('First Name')
    middle_name = StringField('Middle Name')
    last_name = StringField('Last Name')
    prefix = SelectField('Prefix', choices=[('None', 'None'), ('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('miss', 'Miss'), ('dr', 'Dr.'), ('prof', 'Prof.')])
    suffix = SelectField('Suffix', choices=[('None', 'None'), ('jr', 'Jr'), ('sr', 'Sr'), ('ii', 'II'), ('iii', 'III'), ('iv', 'IV')])
    legal_name = StringField('Full Legal Name')
    about = TextAreaField('About')
    country_code = StringField('Country Code')
    mobile_phone = StringField('Mobile Phone')
    country_code2 = StringField('Country Code')
    home_phone = StringField('Home Phone')
    country_code3 = StringField('Country Code')
    work_phone = StringField('Work Phone')
    country_code4 = StringField('Country Code')
    other_phone = StringField('Other Phone')
    email = StringField('Email')
    email2 = StringField('Email 2')
    street1 = StringField('Street')
    city1 = StringField('City')
    state1 = StringField('State/Province')
    postal_code1 = StringField('Postal Code')
    street2 = StringField('Street')
    city2 = StringField('City')
    state2 = StringField('State/Province')
    postal_code2 = StringField('Postal Code')
    company_name = StringField('Company')#+
    company_street = StringField('Street')
    company_city = StringField('City')
    company_state = StringField('State/Province')
    company_postal = StringField('Postal Code')
    company_country = StringField('Country / Region')
    company_department = StringField('Department')
    company_title = StringField('Title')
    birthday = DateTimeField('Birthday', format='%m/%d/%Y %H:%M %p')
    home_anniversary = DateTimeField('Home Anniversary', format="%m/%d/%Y %H:%M %p")
    required = StringField('Required*')
    agent = BooleanField('Agent', default=False)
    vendor = BooleanField('Vendor', default=False)
    investor = BooleanField('Investor', default=False)
    loan_officer = BooleanField('Loan Officer', default=False)
    talent = BooleanField('Talent', default=False)
    builder = BooleanField('Builder', default=False)
    reo = BooleanField('REO', default=False)
    short_sale = BooleanField('Short Sale', default=False)
    expired = BooleanField('Expired', default=False)
    fsbo = BooleanField('FSBO', default=False)
    sphere = BooleanField('Sphere', default=False)
    allied_resource = BooleanField('Allied Resource', default=False)
    referral_sources = BooleanField('Referral Sources', default=False)
    first_time = BooleanField('First Time')
    tags = StringField('Tags')
    notes = TextAreaField('Notes')
    source = StringField('Source')
    other_source = StringField('Other Source')
    date_added = DateTimeField('Added')
    facebook = StringField('Facebook')
    twitter = StringField('Twitter')
    linkedin = StringField('LinkedIn')
    google = StringField('Google+')
    pintrest = StringField('Pintrest')
    instagram = StringField('Instagram')
    houzz = StringField('Houzz')

    submit = SubmitField('Add Contact')
