from app import db
from datetime import datetime


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(64), index=True)
    middle_name = db.Column(db.String(64), index=True)
    last_name = db.Column(db.String(64), index=True)
    prefix = db.Column(db.String)
    suffix = db.Column(db.String)
    legal_name = db.Column(db.String(256), index=True)
    about = db.Column(db.Text)
    country_code = db.Column(db.String(3), index=True)
    home_phone = db.Column(db.String(14), index=True)
    work_phone = db.Column(db.String(14), index=True)
    other_phone = db.Column(db.String(14), index=True)
    email = db.Column(db.String(128), index=True)
    email2 = db.Column(db.String(128), index=True)
    street1 = db.Column(db.String(256), index=True)
    city1 = db.Column(db.String(64), index=True)
    postal_code1 = db.Column(db.String(10), index=True)
    state1 = db.Column(db.String(64), index=True)
    street2 = db.Column(db.String(256), index=True)
    city2 = db.Column(db.String(64), index=True)
    postal_code2 = db.Column(db.String(10), index=True)
    state2 = db.Column(db.String(64), index=True)
    company_street = db.Column(db.String(256), index=True)
    company_city = db.Column(db.String(64), index=True)
    company_state = db.Column(db.String(64), index=True)
    company_postal =  db.Column(db.String(10), index=True)
    company_country = db.Column(db.String(3), index=True)
    company_title = db.Column(db.String(64), index=True)
    company_department = db.Column(db.String(64), index=True)
    birthday = db.Column(db.DateTime, index=True)
    home_anniversary =  db.Column(db.DateTime, index=True)

    agent = db.Column(db.String(64), index=True)
    vendor = db.Column(db.String(64), index=True)
    investor = db.Column(db.String(64), index=True)
    loan_officer = db.Column(db.String(64), index=True)
    talent = db.Column(db.String(64), index=True)
    builder = db.Column(db.String(64), index=True)
    reo = db.Column(db.String(64), index=True)
    short_sale = db.Column(db.DateTime, index=True)
    expired = db.Column(db.DateTime, index=True)
    fsbo = db.Column(db.String(64), index=True)
    sphere = db.Column(db.String(64), index=True)
    allied_resource = db.Column(db.String(64), index=True) 
    referral_sources =  db.Column(db.String(64), index=True)
    first_time =  db.Column(db.Boolean, default=False)
    tags = db.Column(db.String(64), index=True)
    notes = db.Column(db.Text)
    source = db.Column(db.String(64), index=True)
    date_added = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    facebook = db.Column(db.String(256), index=True)
    twitter = db.Column(db.String(256), index=True)
    linkedin = db.Column(db.String(256), index=True)
    google = db.Column(db.String(256), index=True)
    pintrest = db.Column(db.String(256), index=True)
    instagram = db.Column(db.String(256), index=True)
    houzz = db.Column(db.String(64), index=True)
